import { Product, Category, Review, Order } from '@/types';

export const categories: Category[] = [
    { id: 1, name: 'Face Makeup', slug: 'face', icon: '✨', description: 'Foundation, concealer, blush & more', product_count: 28 },
    { id: 2, name: 'Lips', slug: 'lips', icon: '💋', description: 'Lipstick, gloss, lip liner & care', product_count: 35 },
    { id: 3, name: 'Eyes', slug: 'eyes', icon: '👁️', description: 'Eyeshadow, mascara, eyeliner & brows', product_count: 42 },
    { id: 4, name: 'Skincare', slug: 'skincare', icon: '🧴', description: 'Cleansers, serums, moisturizers', product_count: 31 },
    { id: 5, name: 'Nails', slug: 'nails', icon: '💅', description: 'Nail polish, care & accessories', product_count: 18 },
    { id: 6, name: 'Accessories', slug: 'accessories', icon: '🎀', description: 'Brushes, sponges & tools', product_count: 22 },
    { id: 7, name: 'Fragrances', slug: 'fragrances', icon: '🌸', description: 'Perfumes, body mists & sets', product_count: 15 },
    { id: 8, name: 'Hair Care', slug: 'hair', icon: '💇', description: 'Shampoo, conditioner & treatments', product_count: 20 },
];

const generateImage = (seed: string, w = 400, h = 400) =>
    `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const products: Product[] = [
    {
        id: 1,
        name: 'Velvet Matte Lipstick - Rose Petal',
        description: 'A luxurious matte lipstick with a velvety finish that lasts up to 12 hours. Infused with vitamin E and jojoba oil for comfortable wear. The rich Rose Petal shade complements all skin tones beautifully.',
        ingredients: 'Dimethicone, Isododecane, Trimethylsiloxysilicate, Nylon-611/Dimethicone Copolymer, Disteardimonium Hectorite, Vitamin E, Jojoba Oil, Iron Oxides (CI 77491, CI 77492, CI 77499)',
        sku: 'LIP-001',
        category_id: 2,
        category: 'Lips',
        subcategory: 'Lipstick',
        cost_price: 800,
        selling_price: 2499,
        discount_percentage: 0,
        stock_quantity: 45,
        low_stock_alert: 10,
        images: [
            { id: 1, product_id: 1, url: generateImage('lipstick1', 800, 800), public_id: 'lip-001-1', is_primary: true },
            { id: 2, product_id: 1, url: generateImage('lipstick1b', 800, 800), public_id: 'lip-001-2', is_primary: false },
            { id: 3, product_id: 1, url: generateImage('lipstick1c', 800, 800), public_id: 'lip-001-3', is_primary: false },
        ],
        rating: 4.7,
        review_count: 128,
        is_active: true,
        tags: ['matte', 'long-lasting', 'bestseller'],
        created_at: '2026-01-15T10:00:00Z',
        updated_at: '2026-02-28T10:00:00Z',
    },
    {
        id: 2,
        name: 'Silk Radiance Foundation',
        description: 'Medium-to-full coverage foundation with a luminous, skin-like finish. Build able formula that blends seamlessly, providing a flawless base that looks natural all day. SPF 25 protection included.',
        ingredients: 'Water, Cyclopentasiloxane, Titanium Dioxide, Glycerin, Dimethicone, PEG-10, Niacinamide, Hyaluronic Acid, SPF 25 Filters',
        sku: 'FACE-001',
        category_id: 1,
        category: 'Face Makeup',
        subcategory: 'Foundation',
        cost_price: 1200,
        selling_price: 3299,
        discount_percentage: 10,
        stock_quantity: 32,
        low_stock_alert: 10,
        images: [
            { id: 4, product_id: 2, url: generateImage('foundation1', 800, 800), public_id: 'face-001-1', is_primary: true },
            { id: 5, product_id: 2, url: generateImage('foundation1b', 800, 800), public_id: 'face-001-2', is_primary: false },
        ],
        rating: 4.5,
        review_count: 95,
        is_active: true,
        tags: ['foundation', 'SPF', 'luminous'],
        created_at: '2026-01-10T10:00:00Z',
        updated_at: '2026-02-25T10:00:00Z',
    },
    {
        id: 3,
        name: 'Galaxy Eyeshadow Palette',
        description: '18-shade eyeshadow palette featuring a stunning mix of mattes, shimmers, and glitters. Highly pigmented, blendable formula inspired by the cosmos. Perfect for creating any look from daytime chic to evening glam.',
        ingredients: 'Talc, Mica, Silica, Nylon-12, Magnesium Stearate, Dimethicone, Phenoxyethanol, Iron Oxides, Ultramarines, Manganese Violet',
        sku: 'EYE-001',
        category_id: 3,
        category: 'Eyes',
        subcategory: 'Eyeshadow',
        cost_price: 1500,
        selling_price: 3999,
        discount_percentage: 15,
        stock_quantity: 8,
        low_stock_alert: 10,
        images: [
            { id: 6, product_id: 3, url: generateImage('eyeshadow1', 800, 800), public_id: 'eye-001-1', is_primary: true },
            { id: 7, product_id: 3, url: generateImage('eyeshadow1b', 800, 800), public_id: 'eye-001-2', is_primary: false },
        ],
        rating: 4.8,
        review_count: 210,
        is_active: true,
        tags: ['palette', 'shimmer', 'trending'],
        created_at: '2026-01-20T10:00:00Z',
        updated_at: '2026-02-20T10:00:00Z',
    },
    {
        id: 4,
        name: 'Hydra Glow Moisturizer',
        description: 'Lightweight, fast-absorbing moisturizer that delivers intense 48-hour hydration. Enriched with hyaluronic acid and rose water extract for a dewy, radiant complexion. Suitable for all skin types.',
        ingredients: 'Aqua, Glycerin, Hyaluronic Acid, Rosa Damascena Water, Squalane, Niacinamide, Cetearyl Alcohol, Shea Butter, Tocopherol',
        sku: 'SKIN-001',
        category_id: 4,
        category: 'Skincare',
        subcategory: 'Moisturizer',
        cost_price: 900,
        selling_price: 2199,
        stock_quantity: 55,
        low_stock_alert: 10,
        images: [
            { id: 8, product_id: 4, url: generateImage('moisturizer1', 800, 800), public_id: 'skin-001-1', is_primary: true },
        ],
        rating: 4.6,
        review_count: 78,
        is_active: true,
        tags: ['hydrating', 'daily', 'all-skin'],
        created_at: '2026-01-25T10:00:00Z',
        updated_at: '2026-02-15T10:00:00Z',
    },
    {
        id: 5,
        name: 'Precision Liquid Eyeliner',
        description: 'Ultra-fine tip liquid eyeliner for precise, clean lines. Waterproof and smudge-proof formula that lasts all day. Creates sharp wings and detailed eye looks with effortless control.',
        sku: 'EYE-002',
        category_id: 3,
        category: 'Eyes',
        subcategory: 'Eyeliner',
        cost_price: 500,
        selling_price: 1299,
        stock_quantity: 67,
        low_stock_alert: 15,
        images: [
            { id: 9, product_id: 5, url: generateImage('eyeliner1', 800, 800), public_id: 'eye-002-1', is_primary: true },
        ],
        rating: 4.4,
        review_count: 156,
        is_active: true,
        tags: ['waterproof', 'precision'],
        created_at: '2026-02-01T10:00:00Z',
        updated_at: '2026-02-28T10:00:00Z',
    },
    {
        id: 6,
        name: 'Rose Gold Blush Duo',
        description: 'Dual-shade blush compact featuring a soft peach and warm rose gold. Ultra-fine milled powder for a seamless, airbrushed finish. Buildable color that suits all skin tones.',
        sku: 'FACE-002',
        category_id: 1,
        category: 'Face Makeup',
        subcategory: 'Blush',
        cost_price: 700,
        selling_price: 1899,
        discount_percentage: 5,
        stock_quantity: 40,
        low_stock_alert: 10,
        images: [
            { id: 10, product_id: 6, url: generateImage('blush1', 800, 800), public_id: 'face-002-1', is_primary: true },
        ],
        rating: 4.3,
        review_count: 64,
        is_active: true,
        tags: ['duo', 'rose-gold', 'buildable'],
        created_at: '2026-02-05T10:00:00Z',
        updated_at: '2026-02-25T10:00:00Z',
    },
    {
        id: 7,
        name: 'Vitamin C Brightening Serum',
        description: '20% Vitamin C serum combined with niacinamide and ferulic acid for maximum brightening power. Targets dark spots, uneven tone, and dullness. Lightweight texture absorbs quickly.',
        sku: 'SKIN-002',
        category_id: 4,
        category: 'Skincare',
        subcategory: 'Serum',
        cost_price: 1100,
        selling_price: 2799,
        stock_quantity: 28,
        low_stock_alert: 10,
        images: [
            { id: 11, product_id: 7, url: generateImage('serum1', 800, 800), public_id: 'skin-002-1', is_primary: true },
        ],
        rating: 4.9,
        review_count: 230,
        is_active: true,
        tags: ['brightening', 'vitamin-c', 'bestseller'],
        created_at: '2026-01-05T10:00:00Z',
        updated_at: '2026-02-28T10:00:00Z',
    },
    {
        id: 8,
        name: 'Lash Volume Mascara',
        description: 'Dramatic volumizing mascara with a unique hourglass brush that coats every lash. Buildable formula goes from natural to bold in just a few swipes. Flake-free and long-wearing.',
        sku: 'EYE-003',
        category_id: 3,
        category: 'Eyes',
        subcategory: 'Mascara',
        cost_price: 600,
        selling_price: 1599,
        stock_quantity: 5,
        low_stock_alert: 10,
        images: [
            { id: 12, product_id: 8, url: generateImage('mascara1', 800, 800), public_id: 'eye-003-1', is_primary: true },
        ],
        rating: 4.2,
        review_count: 89,
        is_active: true,
        tags: ['volume', 'dramatic', 'low-stock'],
        created_at: '2026-02-10T10:00:00Z',
        updated_at: '2026-02-28T10:00:00Z',
    },
    {
        id: 9,
        name: 'Lip Gloss - Crystal Berry',
        description: 'High-shine lip gloss with a non-sticky formula. The Crystal Berry shade provides a gorgeous berry tint with sparkling micro-shimmers. Enriched with peptides for plumper-looking lips.',
        sku: 'LIP-002',
        category_id: 2,
        category: 'Lips',
        subcategory: 'Lip Gloss',
        cost_price: 400,
        selling_price: 999,
        stock_quantity: 72,
        low_stock_alert: 15,
        images: [
            { id: 13, product_id: 9, url: generateImage('lipgloss1', 800, 800), public_id: 'lip-002-1', is_primary: true },
        ],
        rating: 4.5,
        review_count: 102,
        is_active: true,
        tags: ['gloss', 'shimmer', 'plumping'],
        created_at: '2026-02-08T10:00:00Z',
        updated_at: '2026-02-20T10:00:00Z',
    },
    {
        id: 10,
        name: 'Pro Brush Set - 12 Pieces',
        description: 'Professional-grade makeup brush set with ultra-soft synthetic bristles. Includes brushes for face, eyes, and lips. Rose gold ferrules with a premium vegan leather travel case.',
        sku: 'ACC-001',
        category_id: 6,
        category: 'Accessories',
        subcategory: 'Brush Set',
        cost_price: 1800,
        selling_price: 4499,
        discount_percentage: 20,
        stock_quantity: 15,
        low_stock_alert: 5,
        images: [
            { id: 14, product_id: 10, url: generateImage('brushset1', 800, 800), public_id: 'acc-001-1', is_primary: true },
        ],
        rating: 4.8,
        review_count: 175,
        is_active: true,
        tags: ['brush-set', 'professional', 'vegan'],
        created_at: '2026-01-18T10:00:00Z',
        updated_at: '2026-02-15T10:00:00Z',
    },
    {
        id: 11,
        name: 'Nail Polish - Midnight Cherry',
        description: 'Long-lasting gel-effect nail polish in a deep, glossy cherry shade. Chip-resistant formula with salon-quality shine that lasts up to 10 days. No UV lamp required.',
        sku: 'NAIL-001',
        category_id: 5,
        category: 'Nails',
        subcategory: 'Nail Polish',
        cost_price: 300,
        selling_price: 799,
        stock_quantity: 90,
        low_stock_alert: 20,
        images: [
            { id: 15, product_id: 11, url: generateImage('nailpolish1', 800, 800), public_id: 'nail-001-1', is_primary: true },
        ],
        rating: 4.1,
        review_count: 54,
        is_active: true,
        tags: ['gel-effect', 'cherry'],
        created_at: '2026-02-12T10:00:00Z',
        updated_at: '2026-02-25T10:00:00Z',
    },
    {
        id: 12,
        name: 'Rose Water Setting Spray',
        description: 'Refreshing setting spray infused with real rose water extract. Locks makeup in place for up to 16 hours while giving skin a dewy, natural glow. Can be used before, during, and after makeup application.',
        sku: 'FACE-003',
        category_id: 1,
        category: 'Face Makeup',
        subcategory: 'Setting Spray',
        cost_price: 650,
        selling_price: 1499,
        stock_quantity: 38,
        low_stock_alert: 10,
        images: [
            { id: 16, product_id: 12, url: generateImage('settingspray1', 800, 800), public_id: 'face-003-1', is_primary: true },
        ],
        rating: 4.6,
        review_count: 145,
        is_active: true,
        tags: ['setting-spray', 'rose-water', 'dewy'],
        created_at: '2026-01-28T10:00:00Z',
        updated_at: '2026-02-18T10:00:00Z',
    },
];

export const reviews: Review[] = [
    { id: 1, product_id: 1, user_id: '1', user_name: 'Aisha Khan', rating: 5, comment: 'Amazing color and incredibly long-lasting! Stayed on through coffee, lunch, and dinner. The matte finish is so luxurious.', created_at: '2026-02-15T10:00:00Z' },
    { id: 2, product_id: 1, user_id: '2', user_name: 'Priya Sharma', rating: 5, comment: 'Best lipstick I have ever owned. The shade is perfect for my skin tone and it does not dry out my lips at all!', created_at: '2026-02-20T14:30:00Z' },
    { id: 3, product_id: 1, user_id: '3', user_name: 'Sara Ahmed', rating: 4, comment: 'Beautiful shade and great formula. Only wish it came with a lip liner to match!', created_at: '2026-02-22T09:15:00Z' },
    { id: 4, product_id: 2, user_id: '4', user_name: 'Fatima Ali', rating: 5, comment: 'Finally found a foundation that matches my skin perfectly. The coverage is buildable and it looks so natural!', created_at: '2026-02-18T11:00:00Z' },
    { id: 5, product_id: 2, user_id: '5', user_name: 'Maryam Rizvi', rating: 4, comment: 'Great foundation for everyday wear. Lightweight feel with good coverage. SPF is a bonus!', created_at: '2026-02-25T16:45:00Z' },
    { id: 6, product_id: 3, user_id: '1', user_name: 'Aisha Khan', rating: 5, comment: 'This palette is EVERYTHING! The shimmers are so beautiful and the mattes blend like a dream.', created_at: '2026-02-10T13:00:00Z' },
    { id: 7, product_id: 3, user_id: '6', user_name: 'Zara Hassan', rating: 5, comment: 'So pigmented and blendable. I use this palette almost every day - the shade range is incredible for the price.', created_at: '2026-02-14T10:30:00Z' },
    { id: 8, product_id: 7, user_id: '7', user_name: 'Nadia Malik', rating: 5, comment: 'My skin has never looked better! Dark spots are visibly fading after just 3 weeks of use. Love this serum.', created_at: '2026-02-12T08:00:00Z' },
];

export const orders: Order[] = [
    {
        id: 1,
        order_number: 'SLI-2026-001234',
        user_id: '1',
        customer_name: 'Aisha Khan',
        customer_email: 'aisha@example.com',
        customer_phone: '+92 300 1234567',
        items: [
            { id: 1, order_id: 1, product_id: 1, product_name: 'Velvet Matte Lipstick - Rose Petal', product_image: generateImage('lipstick1', 100, 100), quantity: 2, price_at_purchase: 2499 },
            { id: 2, order_id: 1, product_id: 3, product_name: 'Galaxy Eyeshadow Palette', product_image: generateImage('eyeshadow1', 100, 100), quantity: 1, price_at_purchase: 3399 },
        ],
        subtotal: 8397,
        shipping_cost: 200,
        tax: 420,
        total_amount: 9017,
        status: 'shipped',
        shipping_address: { full_name: 'Aisha Khan', email: 'aisha@example.com', phone: '+92 300 1234567', address: '123 Main Street, DHA Phase 5', city: 'Karachi', postal_code: '75500' },
        shipping_method: 'standard',
        tracking_number: 'TRK-2026-123456',
        payment_method: 'card',
        payment_status: 'paid',
        created_at: '2026-02-28T10:00:00Z',
        updated_at: '2026-03-01T14:00:00Z',
    },
    {
        id: 2,
        order_number: 'SLI-2026-001235',
        user_id: '2',
        customer_name: 'Priya Sharma',
        customer_email: 'priya@example.com',
        customer_phone: '+92 321 9876543',
        items: [
            { id: 3, order_id: 2, product_id: 7, product_name: 'Vitamin C Brightening Serum', product_image: generateImage('serum1', 100, 100), quantity: 1, price_at_purchase: 2799 },
        ],
        subtotal: 2799,
        shipping_cost: 200,
        tax: 150,
        total_amount: 3149,
        status: 'confirmed',
        shipping_address: { full_name: 'Priya Sharma', email: 'priya@example.com', phone: '+92 321 9876543', address: '45 Garden Town', city: 'Lahore', postal_code: '54000' },
        shipping_method: 'express',
        payment_method: 'cod',
        payment_status: 'pending',
        created_at: '2026-02-27T15:00:00Z',
        updated_at: '2026-02-28T09:00:00Z',
    },
    {
        id: 3,
        order_number: 'SLI-2026-001236',
        user_id: '3',
        customer_name: 'Sara Ahmed',
        customer_email: 'sara@example.com',
        customer_phone: '+92 333 5551234',
        items: [
            { id: 4, order_id: 3, product_id: 4, product_name: 'Hydra Glow Moisturizer', product_image: generateImage('moisturizer1', 100, 100), quantity: 2, price_at_purchase: 2199 },
            { id: 5, order_id: 3, product_id: 5, product_name: 'Precision Liquid Eyeliner', product_image: generateImage('eyeliner1', 100, 100), quantity: 1, price_at_purchase: 1299 },
        ],
        subtotal: 5697,
        shipping_cost: 0,
        tax: 285,
        total_amount: 5982,
        status: 'pending',
        shipping_address: { full_name: 'Sara Ahmed', email: 'sara@example.com', phone: '+92 333 5551234', address: '78 XYZ Block, Model Town', city: 'Islamabad', postal_code: '44000' },
        shipping_method: 'standard',
        payment_method: 'bank_transfer',
        payment_status: 'pending',
        created_at: '2026-03-01T08:00:00Z',
        updated_at: '2026-03-01T08:00:00Z',
    },
    {
        id: 4,
        order_number: 'SLI-2026-001237',
        user_id: '4',
        customer_name: 'Fatima Ali',
        customer_email: 'fatima@example.com',
        customer_phone: '+92 345 7890123',
        items: [
            { id: 6, order_id: 4, product_id: 10, product_name: 'Pro Brush Set - 12 Pieces', product_image: generateImage('brushset1', 100, 100), quantity: 1, price_at_purchase: 3599 },
        ],
        subtotal: 3599,
        shipping_cost: 200,
        tax: 190,
        total_amount: 3989,
        status: 'delivered',
        shipping_address: { full_name: 'Fatima Ali', email: 'fatima@example.com', phone: '+92 345 7890123', address: '22 Central Avenue, Gulberg', city: 'Lahore', postal_code: '54660' },
        shipping_method: 'standard',
        tracking_number: 'TRK-2026-789012',
        payment_method: 'card',
        payment_status: 'paid',
        created_at: '2026-02-20T12:00:00Z',
        updated_at: '2026-02-26T18:00:00Z',
    },
    {
        id: 5,
        order_number: 'SLI-2026-001238',
        user_id: '5',
        customer_name: 'Zoya Khan',
        customer_email: 'zoya@example.com',
        customer_phone: '+92 311 2223334',
        items: [
            { id: 7, order_id: 5, product_id: 3, product_name: 'Galaxy Eyeshadow Palette', product_image: generateImage('eyeshadow1', 100, 100), quantity: 1, price_at_purchase: 3999 },
        ],
        subtotal: 3999,
        shipping_cost: 0,
        tax: 200,
        total_amount: 4199,
        status: 'awaiting_payment_approval' as any,
        shipping_address: { full_name: 'Zoya Khan', email: 'zoya@example.com', phone: '+92 311 2223334', address: 'Apartment 4B, Ocean View', city: 'Karachi', postal_code: '74000' },
        shipping_method: 'standard',
        payment_method: 'bank_transfer',
        payment_status: 'pending',
        payment_screenshot_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=400',
        created_at: '2026-03-01T11:00:00Z',
        updated_at: '2026-03-01T11:00:00Z',
    },
];
